### ISSUE TITLE
Pipeline producer overflowed! <RTDE Data Pipeline>

### ISSUE THREAD

**Issue by cindyysi** [UniversalRobots/Universal_Robots_Client_Library#109]
Hi,

This error shows up when emergency stop is pressed.  By looking at the readme, the error happens when the buffer is not read before next package arrives.  What I am confused is that I have a thread that continuously calls `UrDriver->getDataPackage()` until the program shuts down.  I will expect that the buffer is read by this approach even when the emergency stop is triggered.  https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/59 this issue also mentioned that the buffer needs to be emptied by `getDataPackage()` call.  Am I misunderstanding or missing anything here?  Thank you!

**Comment by fmauch** [comment]
Hitting the EM-Stop should not shut down the RTDE connection. I currently don't have access to a robot to try reproduce this, let me come back to that next week.

Do you have any custom setup of your robot? Any fieldbusses configured, external safety system wired to the robot?
