### ISSUE TITLE
[start_ursim] Script does not check ursim version

### ISSUE THREAD

**Issue by RobertWilbrandt** [UniversalRobots/Universal_Robots_Client_Library#191]
`start_ursim` does not check if the used ursim version is up-to-date. This can lead to the following problem:
1. Having used the script earlier, docker pulled a version that was current at the time of use.
2. The ur20 is released and the driver now passes this robot model to ursim.
3. The old version does not know that version string and defaults to a ur5e.

This leads to no visible errors and unexpected results.

**Comment by gavanderhoorn** [comment]
I believe this is a related issue: https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/842.

**Comment by VinDp** [comment]
This issue is solved by [#203](https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/203).
