### ISSUE TITLE
UR5透過 RPC 取得資料 getDataPackage 實作

### ISSUE THREAD

**Issue by sk413025** [UniversalRobots/Universal_Robots_Client_Library#83]
https://github.com/UniversalRobots/Universal_Robots_Client_Library/blob/125f4f7a48b299b07e298cf479e3ba6882c3af3a/src/rtde/rtde_client.cpp#L347-L360

**Comment by fmauch** [comment]
I cannot quite follow this issue's intention. Could you please elaborate a bit more?

**Comment by sk413025** [comment]
Sorry I didn't notice the copy-paste to the wrong place.  I closed the issue because I couldn't delete it.
